Сделал разметку главной страницы
htmlacademy-htmlcss/81933-sedona-29 pull request #2
Opened 2020-09-12 20:22 UTC by Reyner2020

домашнее задание 2.7

2020-09-13 12:15 UTC, nikkypizza requested changes

2020-09-13 12:15 UTC, nikkypizza commented on index.html
> +				<ul>
Почему бы не обернуть этот список в отдельный блок, как у тебя сделано с блоком **Жильё/Еда/Сувениры**?

2020-09-13 12:15 UTC, nikkypizza commented on index.html
> +  				  и мы покажем вам лучшие предложения гостиниц в седоне  </p>
Тег `<b>` используется для придания жирности маленьким кусочкам текста внутри параграфов, тут же у тебя полноценный заголовок

2020-09-13 12:15 UTC, nikkypizza commented on index.html
> +  					<li><a href="#">Ютуб</a></li>
Тут и в `Разработано HTML Academy` должны быть изображения

2020-09-13 12:15 UTC, nikkypizza commented on index.html
> +  			</section>
Тут не хватает блока с картой. На данный момент изображения будет достаточно, но в будущем [добавим интерактивную карту](https://up.htmlacademy.ru/htmlcss/29/criteries#d18)

2020-09-13 18:22 UTC, Reyner2020 commented on index.html
> +  				<a href="blank.html">Вход</a>
Понял, никакой больше импровизации)

2020-09-13 18:22 UTC, Reyner2020 commented on index.html
> +  			<img src="https://via.placeholder.com/1200x509" alt="Sedona Welcome">
Тут не совсем понял "В макете изображение идет перед заголовком", у меня вроде так и есть, заголовок и после изображение, или имеется ввиду что тег <p>, а после уже изображение вставлять?

2020-09-13 18:24 UTC, Reyner2020 commented on index.html
> +  			<img src="https://via.placeholder.com/1200x509" alt="Sedona Welcome">
Или это было не утверждение) тогда сейчас сделаю как в макете - картинка, а под ней заголовок

2020-09-13 18:48 UTC, Reyner2020 commented on index.html
> +  			<section>
может я не так понял на лекции, но мне показалось, что warning в валидаторе носит рекомендательный характер, я вчера тоже через валидатор прогонял код. Но на лекции еще Вадим в подобной разметке не стал разработчкика в заголовок оборачивать, сказав, что этого мало для заголовка, я это запомнил и тоже не стал "Разработано" оборачивать в заголовок

2020-09-14 08:16 UTC, nikkypizza commented on index.html
> +  			<section>
@Reyner2020 да, носит рекомендательный характер, но если мы можем избавиться от предупреждения, почему бы это не сделать?) 
Разработано и не нужно оборачивать в заголовок это верно. Я бы просто не оборачивал в секцию, потому что для секции тут тоже мало контента. Обычный див бы тут сгодился, ничего постыдного в нем нет.

2020-09-14 08:37 UTC, nikkypizza approved these changes
Оставил пару стилевых комментариев, поправь к следующему заданию. В будущем еще придется править верстку, когда будем стилизовать, но на сейчас все ок :)
Если будут возникать вопросы можешь писать мне в Телеграм - nikkypizza. Это может помочь сэкономить время)

2020-09-14 08:37 UTC, nikkypizza commented on index.html
> +    <img src="https://via.placeholder.com/800x256" alt="причина 1">
Тут альт с цифрой остался, и всё еще не у всех картинок есть атрибуты `width` и `height`

2020-09-14 08:37 UTC, nikkypizza commented on index.html
> +  </p>
Тег параграфа создает перенос строки, потому тут можно обойтись без `<br>`
```suggestion
  <p>#visitSEDONA</p>
    Тел: <a href="tel:+74956660166">+7 (495) 666-01-66</a>
```

2020-09-14 08:37 UTC, nikkypizza commented on index.html
> +  <h1>Седона — небольшой городок в Аризоне,  заслуживающий большего! </h1>
Всё еще остались битые символы, которые видно в превью
![image](https://user-images.githubusercontent.com/30810655/93062435-976bf100-f67d-11ea-985d-e90791794b44.png)

2020-09-14 08:37 UTC, nikkypizza commented on index.html
> +  <h1>Седона — небольшой городок в Аризоне,  заслуживающий большего! </h1>
И есть лишние пробелы на концах строк. Возможно стоит включить подсветку пробелов в твоем редакторе, чтобы их было видно
![image](https://user-images.githubusercontent.com/30810655/93062647-ec0f6c00-f67d-11ea-845c-8b923a987336.png)

2020-09-14 08:37 UTC, merged