Домашнее задание по раставлению классов
htmlacademy-htmlcss/81933-sedona-29 pull request #3
Opened 2020-09-24 15:21 UTC by Reyner2020

Извиняюсь за медлительность, только только начинаю возвращаться в учебный процесс, буду нагонять.

2020-09-25 08:19 UTC, nikkypizza requested changes
- Стоит пройтись еще раз перепроверить все цвета и размеры и сверить визуально с макетом
- Также нужно привести отступы в html к единому виду, сейчас они стоят наугад и тяжело понять какой элемент во что вложен

**As is:**
![image](https://user-images.githubusercontent.com/30810655/94243859-b2155400-ff20-11ea-9d28-f8e9a7433316.png)
**To be:**
![image](https://user-images.githubusercontent.com/30810655/94243924-c6595100-ff20-11ea-8d7d-ce8cbf7ffb64.png)

-----
О форматировании [писал тут](https://github.com/htmlacademy-htmlcss/81933-sedona-29/pull/2#discussion_r487518783). Для этой задачи используются плагины для редактора, стоит с этим разобраться

2020-09-25 08:19 UTC, nikkypizza commented on index.html
> +  <p class="footer-copyright">Разработано <a class="button" href="https://htmlacademy.ru"><img src="img/icon-htmlacademy.svg" width="115" height="41" alt="HTML Acedemy"></a></p>
Тут правильнее называть ссылку `class="link"`. Не стоит смешивать кнопки с ссылками

2020-09-25 08:19 UTC, nikkypizza commented on index.html
> +   <li class="reasons-item">
Класс `reasons-item` стоит добавить для всех элементов списка, а не только для первого. Аналогично с `features-item`

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +  background-repeat: no-repeat;
Не уверен, что у `body` есть какое-то фоновое изображение. О каком изображении речь?

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +  background-color: transparent;
```suggestion

```
Прозрачность ни к чему

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +}
```suggestion
```
Этого класса нет в разметке. Если речь об активной вкладке на внутренней странице, то у нее меняется не фон, а цвет текста. Оставим пока внутреннюю страницу, сейчас главная в приоритете

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +.user-navigation a:focus {
`user-navigation` нет в разметке

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +  vertical-align: middle;
```suggestion
```

Это правило используется для выравнивания текста в таблицах

2020-09-25 08:19 UTC, nikkypizza commented on css/Style.css
> +  color: var(--basic-white);
По макету тут должен быть черный

2020-09-25 08:19 UTC, nikkypizza commented on index.html
>       <img src="img/index-logo.svg" width="138" height="70" alt="Логотип Седона">
```suggestion
     <img src="img/index-logo.svg" width="138" height="70" alt="Логотип Седона">
```

2020-10-04 11:40 UTC, Reyner2020 commented on index.html
>    <h1>Седона — небольшой городок в Аризоне,  заслуживающий большего! </h1>
да, разберусь с этими невидимыми символами, потому что мне их нигде не видно, наверное это от фигмы, потому что я текст оттуда копирую. а что за сайт, где проверять на невидимость?) и еще по читаемости кода, я после первых коментов погуглил, и делаю в саблайме следующее: cmd a, Edit - Line - Reindent, вроде как форматирует код от лишних отступов и прочего, но сейчас повнимательнее всмотрелся и да он как то странно это делает, его как то надо наверное настраивать или я вообще не тем инструментом для этого пользуюсь?

2020-10-04 12:04 UTC, Reyner2020 commented on index.html
> +  <button class="button">Поиск гостиницы в Седоне</button>
переписал немного разметку, в макете же кнопка поиска "Найти" и с голубым цветом, переписал название, ну и текста накидал для будущей формы поиска, а коричневая это же просто плашка как я понимаю.

2020-10-04 17:11 UTC, nikkypizza commented on index.html
> +  <link href="css/style.css" rel="stylesheet">
[в превью](https://htmlacademy-htmlcss.github.io/81933-sedona-29/3/) стили не подгружаются. Это происходит потому, что у тебя файл именован с большой буквы, а подключен с маленькой.

Когда открываешь проект локально браузер может игнорировать регист, и подгружать файл как есть, при публикации требуется строгое соответствие.

К слову, по критериям запрещено использовать прописные буквы в названиях файлов

2020-10-20 09:07 UTC, merged